Description: Creates resource stack for mpows.

Parameters:
  CapturePageLoads:
    Type: String
    Default: true
    AllowedValues:
      - true
      - false

  CapturePageClicks:
    Type: String
    Default: true
    AllowedValues:
      - true
      - false
    
  DataStreamShardsForPageLoads:
    Type: Number
    Default: 1

  DataStreamShardsForPageClicks:
    Type: Number
    Default: 1

Conditions:
  CreatePageLoadResources: !Equals [ !Ref CapturePageLoads, true ]
  CreatePageClickResources: !Equals [ !Ref CapturePageClicks, true ]

Resources:
  S3BucketPageLoads:
    Type: 'AWS::S3::Bucket'
    Condition: CreatePageLoadResources 
    Properties:
      BucketName: !Sub "mpaws-${AWS::AccountId}-${AWS::Region}-page-loads"
      Tags:
        - Key: Vendor
          Value: mpows
      PublicAccessBlockConfiguration:
        BlockPublicAcls : true
        BlockPublicPolicy : true
        IgnorePublicAcls : true
        RestrictPublicBuckets : true

  S3BucketPageClicks:
    Type: 'AWS::S3::Bucket'
    Condition: CreatePageClickResources
    Properties:
      BucketName: !Sub "mpaws-${AWS::AccountId}-${AWS::Region}-page-clicks"
      Tags:
        - Key: Vendor
          Value: mpows
      PublicAccessBlockConfiguration:
        BlockPublicAcls : true
        BlockPublicPolicy : true
        IgnorePublicAcls : true
        RestrictPublicBuckets : true

  KinesisDataStreamPageLoads:
    Type: AWS::Kinesis::Stream
    Condition: CreatePageLoadResources
    Properties: 
      Name: !Sub "mpaws-${AWS::AccountId}-${AWS::Region}-page-loads-stream"
      RetentionPeriodHours: 24
      ShardCount: !Ref DataStreamShardsForPageLoads
      Tags: 
        - Key: Vendor
          Value: mpows
        - Key: Name
          Value: !Sub "mpaws-${AWS::AccountId}-${AWS::Region}-page-loads-stream"

  KinesisDataStreamPageClicks:
    Type: AWS::Kinesis::Stream
    Condition: CreatePageClickResources
    Properties: 
      Name: !Sub "mpaws-${AWS::AccountId}-${AWS::Region}-page-clicks-stream"
      RetentionPeriodHours: 24
      ShardCount: !Ref DataStreamShardsForPageClicks
      Tags: 
        - Key: Vendor
          Value: mpows
        - Key: Name
          Value: !Sub "mpaws-${AWS::AccountId}-${AWS::Region}-page-clicks-stream"

  FirehoseDeliveryIAMRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Sid: ''
          Effect: Allow
          Principal:
            Service: firehose.amazonaws.com
          Action: sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: root
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: "s3:*"
                Resource: "*"

  KinesisSourceIAMRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Sid: ''
          Effect: Allow
          Principal:
            Service: firehose.amazonaws.com
          Action: sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: root
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: "kinesis:*"
                Resource: "*"            

  KinesisFirehosePageLoads:
    Type: AWS::KinesisFirehose::DeliveryStream
    Condition: CreatePageLoadResources
    Properties: 
      DeliveryStreamName: !Sub "mpaws-${AWS::AccountId}-${AWS::Region}-page-loads-firehose"
      DeliveryStreamType: KinesisStreamAsSource
      KinesisStreamSourceConfiguration: 
        KinesisStreamARN: !GetAtt KinesisDataStreamPageLoads.Arn
        RoleARN: !GetAtt KinesisSourceIAMRole.Arn
      S3DestinationConfiguration: 
        BucketARN: !GetAtt S3BucketPageLoads.Arn
        RoleARN: !GetAtt FirehoseDeliveryIAMRole.Arn
        BufferingHints:
          IntervalInSeconds: 300
          SizeInMBs: 5
      Tags: 
        - Key: Vendor
          Value: mpows
        - Key: Name
          Value: !Sub "mpaws-${AWS::AccountId}-${AWS::Region}-page-loads-firehose"         

  KinesisFirehosePageClicks:
    Type: AWS::KinesisFirehose::DeliveryStream
    Condition: CreatePageClickResources
    Properties: 
      DeliveryStreamName: !Sub "mpaws-${AWS::AccountId}-${AWS::Region}-page-clicks-firehose"
      DeliveryStreamType: KinesisStreamAsSource
      KinesisStreamSourceConfiguration: 
        KinesisStreamARN: !GetAtt KinesisDataStreamPageClicks.Arn
        RoleARN: !GetAtt KinesisSourceIAMRole.Arn
      S3DestinationConfiguration: 
        BucketARN: !GetAtt S3BucketPageClicks.Arn
        RoleARN: !GetAtt FirehoseDeliveryIAMRole.Arn
        BufferingHints:
          IntervalInSeconds: 300
          SizeInMBs: 5
      Tags: 
        - Key: Vendor
          Value: mpows
        - Key: Name
          Value: !Sub "mpaws-${AWS::AccountId}-${AWS::Region}-page-clicks-firehose"         